### ISSUE TITLE
`flux` panics inside `ena`

### ISSUE THREAD

**Issue by Samir-Rashid** [flux-rs/flux#662]
Hello. I am using `flux`, and I have found a reproducer for a panic in flux. Flux appears to be panicking inside [`ena`](https://github.com/rust-lang/ena).

This could be related to #578. I was able to make the following minimal reproducer.
```rs
pub fn baz(v: &mut Vec<i32>) {
    v.iter_mut().for_each(|x| *x *= 2);
}
```

```
thread 'rustc' panicked at /rust/deps/ena-0.14.3/src/snapshot_vec.rs:199:10:
index out of bounds: the len is 9 but the index is 16
```

Original content of issue before I found minimal reproducer:
<details>
The following line under the TODO is the exact line which induces the panic.
```rs
    fn reset_config(&self, config: &mut Self::MpuConfig) {
        // TODO: This iterator causes flux to panic
        config.regions.iter_mut().for_each(|region| {
            *region = (
                TORUserPMPCFG::OFF,
                core::ptr::null::<u8>(),
                core::ptr::null::<u8>(),
            )
        });
```
[The exact code I used to isolate this line is on this branch.](https://github.com/PLSysSec/tock/blob/flux-bug-iterator/arch/rv32i/src/pmp.rs#L632-L639) I also have a version which passes refinement and triggers the panic on the `refine-pmp` branch (commit f702f0).

## To reproduce:
`git clone https://github.com/PLSysSec/tock.git && cd tock/arch/rv32i && cargo flux`

```
$ cargo flux
    Checking rv32i v0.1.0 (/vtock/arch/rv32i)
thread 'rustc' panicked at /rust/deps/ena-0.14.3/src/snapshot_vec.rs:199:10:
index out of bounds: the len is 10 but the index is 22
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: could not compile `rv32i` (lib)
```
with backtrace:
```
$ RUST_BACKTRACE=1 cargo flux
    Checking rv32i v0.1.0 (//vtock/arch/rv32i)
thread 'rustc' panicked at /rust/deps/ena-0.14.3/src/snapshot_vec.rs:199:10:
index out of bounds: the len is 10 but the index is 22
stack backtrace:
   0: rust_begin_unwind
             at /rustc/cc8da78a036dc3c15c35a97651b02af9a6d30c1e/library/std/src/panicking.rs:661:5
   1: core::panicking::panic_fmt
             at /rustc/cc8da78a036dc3c15c35a97651b02af9a6d30c1e/library/core/src/panicking.rs:74:14
   2: core::panicking::panic_bounds_check
             at /rustc/cc8da78a036dc3c15c35a97651b02af9a6d30c1e/library/core/src/panicking.rs:276:5
   3: <ena::unify::UnificationTable<ena::unify::backing_vec::InPlace<rustc_middle::infer::unify_key::RegionVidKey, &mut alloc::vec::Vec<ena::unify::VarValue<rustc_middle::infer::unify_key::RegionVidKey>>, &mut rustc_infer::infer::snapshot::undo_log::InferCtxtUndoLogs>>>::uninlined_get_root_key.llvm.5690312405728768494.cold
   4: <rustc_infer::infer::relate::type_relating::TypeRelating as rustc_type_ir::relate::TypeRelation<rustc_middle::ty::context::TyCtxt>>::regions
   5: <rustc_infer::infer::InferCtxt>::super_combine_tys::<rustc_infer::infer::relate::type_relating::TypeRelating>
   6: <rustc_infer::infer::relate::type_relating::TypeRelating as rustc_type_ir::relate::TypeRelation<rustc_middle::ty::context::TyCtxt>>::tys
   7: <rustc_trait_selection::traits::select::SelectionContext>::poly_select::{closure#0}
   8: <rustc_trait_selection::traits::select::SelectionContext>::select
   9: <flux_middle::rty::projections::Normalizer as flux_middle::rty::fold::FallibleTypeFolder>::try_fold_ty
  10: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
  11: core::iter::adapters::try_process
  12: <flux_middle::rty::FnSig as flux_middle::rty::fold::TypeFoldable>::try_fold_with
  13: <flux_middle::rty::Binder<T> as flux_middle::rty::fold::TypeSuperFoldable>::try_super_fold_with
  14: flux_refineck::checker::Checker<M>::run
  15: flux_refineck::checker::Checker<M>::check_closure_obligs
  16: flux_refineck::checker::Checker<M>::check_call
  17: flux_refineck::checker::Checker<M>::check_basic_block
  18: flux_refineck::checker::Checker<M>::check_goto
  19: flux_refineck::checker::Checker<M>::check_basic_block
  20: flux_refineck::checker::Checker<M>::check_goto
  21: flux_refineck::checker::Checker<M>::run
  22: tracing::span::Span::in_scope
  23: flux_refineck::checker::Checker<flux_refineck::checker::ShapeMode>::run_in_shape_mode
  24: tracing::span::Span::in_scope
  25: flux_refineck::check_fn
  26: flux_driver::callbacks::CrateChecker::check_def
  27: tracing::span::Span::in_scope
  28: flux_middle::global_env::GlobalEnv::enter
  29: rustc_middle::ty::context::GlobalCtxt::enter
  30: <flux_driver::callbacks::FluxCallbacks as rustc_driver_impl::Callbacks>::after_analysis
  31: rustc_interface::interface::run_compiler::<core::result::Result<(), rustc_span::ErrorGuaranteed>, rustc_driver_impl::run_compiler::{closure#0}>::{closure#1}
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
error: could not compile `rv32i` (lib)
```
</details>

**Comment by ranjitjhala** [comment]
Thanks @Samir-Rashid -- I will take a look asap!

**Comment by nilehmann** [comment]
This was fixed in https://github.com/flux-rs/flux/pull/659. I added a test for this reproducer https://github.com/flux-rs/flux/commit/fd4523a21e6dbefb4ba3aa35fbc4697e304f4a1d
