### ISSUE TITLE
ICE with const-generic signature

### ISSUE THREAD

**Issue by ranjitjhala** [flux-rs/flux#885]
The code below 

```rust
#[flux::sig(fn (head: _, rows: _) -> usize)]
fn csv<const N: usize>(head: [&str; N], rows: &[[&str; N]]) -> usize {
    0
}
```

makes flux keel over with

```
 --> tests/tests/todo/boo.rs:2:4
  |
2 | fn csv<const N: usize>(head: [&str; N], rows: &[[&str; N]]) -> usize {
  |    ^^^
-Ztrack-diagnostics: created at compiler/rustc_passes/src/dead.rs:1114:18
  |
  = note: `#[warn(dead_code)]` on by default

thread 'rustc' panicked at crates/flux-fhir-analysis/src/conv/struct_compat.rs:526:22:
attempt to subtract with overflow
```

**Comment by nilehmann** [comment]
This must be related to these changes https://github.com/flux-rs/flux/pull/884. Struct compact requires some complicated de Bruijn index juggling

**Comment by ranjitjhala** [comment]
@nilehmann any idea what is going on here? Seems like some glitch in `adjust_bvars` ?

**Comment by ranjitjhala** [comment]
Looks like this works instead

```rust
#[flux::sig(fn (rows: &[_]))]
fn csv<const N: usize>(rows: &[[&str; N]]) {}
```

**Comment by nilehmann** [comment]
That code fills in holes by matching against the default signature. When we found match, the hole and the matching type could be under a different number of binders so we try to adjust de Bruijn indices. It's a confusing computation and I just probably got it wrong.
